### ISSUE TITLE
Moving/disabling transfer icon

### ISSUE THREAD

**Issue by slowiu06** [Corail31/travel_bag#1]
Icon which tranfers all items to player inventory covers Quark inventory sorting icon. The best solution is to add config to turn off/move this icon.
![image](https://user-images.githubusercontent.com/7887594/69550974-3b27cb80-0f9c-11ea-9b37-d3e443a83e89.png)

**Comment by slowiu06** [comment]
I also noticed that when I use the button to automatically move items from inventory to the bag (with Quark mod), when I have more than it should fit in, they still fit in the bag, although they are invisible. When I make some space in my bag and use sorting, the items take up empty spaces.

**Comment by Corail31** [comment]
I could adapt it when when quark is present.
I'm not sure what you mean in your second comment, are you asking me why the quark button is not working or you're using the travel bag button ? - to transfer all items in the player's inventory and drop any items on ground if not enough space -

**Comment by slowiu06** [comment]
I also noticed that when I use the button (from Quark mod) to automatically move items from my inventory to the Travel Bag , when I have more items in EQ than should fit in Travel Bag, they still can be stored in the bag, although they are invisible (so Travel Bag can practically store More items than it should). Next, when I move items from Travel Bag to my inventory and make some space in my Travel Bag and after that use Sorting Button (from Quark), the invisible items take up empty spaces.

**Comment by Corail31** [comment]
Ah yes, i see, it's true the items exist if the inventory is resized, because if Tombstone is not present, the bag can't be enchanted, and it resizes to a smaller bag, but if you add again Tombstone, the items are still present.

**Comment by Corail31** [comment]
@slowiu06 I made the tests.
I can add a client config opton to hide the button to transfer (as quark is in modules, and it has options to hide the inventory buttons too, and one of them transfers all the items).
Then, Quark has hard to display the buttons at the right place as i think it remembers where the slots were, or is based on a 9 slots by line inventory.
So, when the inventory is enlarge with a Tombstone's soul, the buttons near the title looks sticked to this title. I don't think this part is on my side. (as jei has no trouble to display correctly on side)
