### ISSUE TITLE
[1.15.1] Missing Texture for Corail Bag Slots

### ISSUE THREAD

**Issue by realTIMematrix** [Corail31/travel_bag#2]
Hi,

I'm using the following mods:

- Travel Bag 1.0.8 for 1.15.1
- Minecraft-Version: 1.15.1
- forge-30.0.41
- curios-FORGE-1.15.1-2.0-beta.jar

The two Bag Slots your mod create does have missing textures until they get used with the Bag. It seems that there are no registered icons. See reference link:

[https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Developers#registering-curio-slot-icons](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Developers#registering-curio-slot-icons)

**Comment by Corail31** [comment]
Hi realTIMematrix, this line is present.
https://github.com/Corail31/travel_bag/blob/master/src/main/java/ovh/corail/travel_bag/compatibility/CompatibilityCurios.java#L41
I'll see with Illusive if something changed for the path.
