### ISSUE TITLE
Curios Button Reset

### ISSUE THREAD

**Issue by MilitaryFool** [Corail31/travel_bag#3]
When I log into my modded Minecraft account and start up a world, if I had defined the open buttons for the two bag slots they will have been reset on the new log in. I do not know if this is a mod incompatibility or a bug in this mod itself along with Curios API.

**Comment by Corail31** [comment]
It's an intended feature, by default, the mod doesn't add custom keybinds (users generally don't like default keybinds) and it's their choice to define them for this behavior or not.

**Comment by ProsperCraft** [comment]
I can confirm this is a bug and happening to me as well.

**Comment by ProsperCraft** [comment]
@MilitaryFool Did you bind your key to a mouse button or a keyboard key?

**Comment by MilitaryFool** [comment]
I have found that the issue has come to light in the newest version 1.1.0 but does not exist in the previous 1.0.8

**Comment by MilitaryFool** [comment]
@ProsperCraft I bound them to the “i” and “o” keys on my keyboard.

**Comment by Corail31** [comment]
@MilitaryFool Thanks for your test, your informations were helpful.
May you test this [FIXE](https://cdn.discordapp.com/attachments/429050628044488705/688425184566444105/travel_bag-1.1.0-1.15.2.jar) ? :)

**Comment by MilitaryFool** [comment]
@Corail31 This patch seems to have worked thank you very much!

**Comment by Corail31** [comment]
can you also contact me on curseForge for a small reward when using tombstone for your time spent ?
